# Generated by Django 2.2.2 on 2019-10-18 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=10)),
                ('tag_info', models.TextField(null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('index', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.SiteTag')),
            ],
        ),
    ]
