# Generated by Django 2.2.2 on 2019-10-18 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='index',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='tags',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.SiteTag'),
        ),
    ]
