# Generated by Django 2.2.2 on 2019-10-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191018_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='tags',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='website.SiteTag'),
        ),
    ]
