# Generated by Django 2.2.6 on 2019-10-20 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20191018_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=20)),
                ('attach', models.FileField(upload_to='uploads/<django.db.models.fields.CharField>/%Y/%m/%d/', verbose_name='添付ファイル')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
