# Generated by Django 2.2.6 on 2019-10-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191021_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='thumbnail',
            field=models.ForeignKey(default=1, on_delete=False, to='website.MediaImage'),
            preserve_default=False,
        ),
    ]
