# Generated by Django 2.2.6 on 2019-10-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191021_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.MediaImage'),
        ),
    ]
